version: '3.4'

services:
  webapp:
    image: osavoskin/eshopondapr-webapp:latest
    build:
      context: ../
      dockerfile: ./EShop.WebApp/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3551
      - DISABLE_SIDEKICK=true
    depends_on:
      - redis
      - zipkin
      - catalog-dapr
      - ordering-dapr
      - payment-dapr
    ports:
      - "8888:80"
    networks:
      - eshop-on-dapr 
      
  webapp-dapr:
    image: "daprio/daprd:1.7.4"
    command: [
      "./daprd",
      "-app-id", "webapp",
      "-app-port", "80",
      "-dapr-http-port", "3551",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./Dapr/Components/:/components"
      - "./Dapr/Config/:/config"
    depends_on:
      - webapp
    network_mode: "service:webapp"

  catalog:
    image: osavoskin/eshopondapr-catalog:latest
    build:
      context: ../
      dockerfile: ./EShop.Catalog/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3552
      - DISABLE_SIDEKICK=true
    depends_on:
      - redis
      - zipkin
    networks:
      - eshop-on-dapr
      
  catalog-dapr:
    image: "daprio/daprd:1.7.4"
    command: [
      "./daprd",
      "-app-id", "catalog",
      "-app-port", "80",
      "-dapr-http-port", "3552",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./Dapr/Components/:/components"
      - "./Dapr/Config/:/config"
    depends_on:
      - catalog
    network_mode: "service:catalog"
     
  ordering:
    image: osavoskin/eshopondapr-ordering:latest
    build:
      context: ../
      dockerfile: ./EShop.Ordering/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3553
      - DISABLE_SIDEKICK=true
    depends_on:
      - redis
      - zipkin
      - placement
    networks:
      - eshop-on-dapr  
      
  ordering-dapr:
    image: "daprio/daprd:1.7.4"
    command: [
      "./daprd",
      "-app-id", "ordering",
      "-app-port", "80",
      "-dapr-http-port", "3553",
      "-placement-host-address", "placement:50006",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./Dapr/Components/:/components"
      - "./Dapr/Config/:/config"
    depends_on:
      - ordering
    network_mode: "service:ordering"
    
  payment:
    image: osavoskin/eshopondapr-payment:latest
    build:
      context: ../
      dockerfile: ./EShop.Payment/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3554
      - DISABLE_SIDEKICK=true
    depends_on:
      - redis
      - zipkin
    networks:
      - eshop-on-dapr 
      
  payment-dapr:
    image: "daprio/daprd:1.7.4"
    command: [
      "./daprd",
      "-app-id", "payment",
      "-app-port", "80",
      "-dapr-http-port", "3554",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./Dapr/Components/:/components"
      - "./Dapr/Config/:/config"
    depends_on:
      - payment
    network_mode: "service:payment"
       
  placement:
    image: "daprio/dapr:1.7.3"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - eshop-on-dapr
    
  redis:
    image: "redis:7.0-alpine"
    ports:
      - "6380:6379"
    networks:
      - eshop-on-dapr
      
  zipkin:
    image: "openzipkin/zipkin:2.23.4"
    ports:
      - "9412:9411"
    networks:
      - eshop-on-dapr
      
networks:
  eshop-on-dapr:
    driver: bridge