version: '3.4'

services:
  catalog:
    image: osavoskin/eshopondapr-catalog:latest
    build:
      context: ../
      dockerfile: ../EShop.Catalog/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    depends_on:
      - redis
      - zipkin
      - placement
    networks:
      - eshop-on-dapr
      
  catalog-dapr:
    image: "daprio/daprd:1.7.3"
    command: [
      "./daprd",
      "-app-id", "catalog",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",
      "-components-path", "/components",
      "-config", "/config/config.yaml"]
    volumes:
      - "./Dapr/Components/:/components"
      - "./Dapr/Config/:/config"
    depends_on:
      - catalog
    network_mode: "service:catalog"
    
  placement:
    image: "daprio/dapr:1.7.3"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - eshop-on-dapr
    
  redis:
    image: "redis:7.0-alpine"
    ports:
      - "6380:6379"
    networks:
      - eshop-on-dapr
      
  zipkin:
    image: "openzipkin/zipkin:2.23.4"
    ports:
      - "9412:9411"
    networks:
      - eshop-on-dapr
      
networks:
  eshop-on-dapr:
    driver: bridge